import {zoo,config,tokenFor,readToken} from '@/lib/zoowork';
import {z} from 'zod';
import {getTaste,userId} from '@/lib/memory-store';
import {tasteSchema} from '@/lib/taste';
import {researchWithTavily,type ResearchContext} from '@/lib/tavily';
const criteriaSchema=z.array(z.object({id:z.string().max(80),label:z.string().max(120),selected:z.boolean(),weight:z.number().min(0).max(100),reason:z.string().max(1000),hard:z.boolean().optional(),tasteReason:z.string().max(1000).optional()})).min(1).max(20);
const inferenceSchema=z.object({domain:z.string(),criteria:criteriaSchema,forgotten:z.array(z.object({id:z.string(),explanation:z.string()})).max(5)});
const researchSchema=z.object({candidates:z.array(z.object({id:z.string(),name:z.string(),subtitle:z.string(),price:z.union([z.string(),z.number()]).nullable().transform(v=>typeof v==='number'?String(v)+' (reported price)':v),url:z.string().nullable().transform(v=>v&&/^https?:\/\//i.test(v)?v:null),scores:z.record(z.number().min(0).max(100).nullable()),evidence:z.record(z.string().nullable().transform(v=>v||'No verified evidence available.')),caveat:z.string(),verified:z.boolean().optional()})).max(8),error:z.string().optional()});
export async function POST(request:Request){try{const owner=userId(request);const input:any=await request.json();const query=z.string().min(8).max(1500).parse(input.query);const {agent}=config();if(!agent)return Response.json({error:'Live research is not configured yet. Try the interactive demo.'},{status:503});let session:string;
 if(input.phase==='research'){criteriaSchema.parse(input.criteria);const data=await readToken(input.token);if(data.owner!==owner)throw new Error('This decision belongs to another account.');session=data.session;}else if(input.phase==='criteria'){await zoo('/agents/'+agent+'/start',{});const s=await zoo('/agents/'+agent+'/sessions',{});session=s.session_id;}else return Response.json({error:'Unknown phase'},{status:400});
 const started=Date.now();let research:ResearchContext|undefined;
 if(input.phase==='research'&&process.env.TAVILY_API_KEY)research=await researchWithTavily(query,criteriaSchema.parse(input.criteria));
 const preferenceMemory=await getTaste(owner);const recalledIds=z.array(z.string().max(100)).max(4).optional().parse(input.recalledIds);const recalled=preferenceMemory.memories.filter(m=>recalledIds?.includes(m.id));const content=JSON.stringify({recalled_memories:input.useTaste===false?[]:recalled,preference_memory:input.useTaste===false?undefined:preferenceMemory.profile,remembered_decisions:input.useTaste===false?[]:preferenceMemory.memories.slice(0,12),phase:input.phase,query,criteria:input.phase==='research'?input.criteria:undefined,research_context:research});const receipts=await zoo('/agents/'+agent+'/sessions/'+session+'/events',{events:[{type:'user.message',content}]});const list=Array.isArray(receipts)?receipts:receipts.receipts||receipts.events;if(list&&list[0]?.accepted===false)throw new Error('ZooWork did not accept the request.');const metadata=research?{provider:research.provider,sourceUrls:research.sources.map(s=>s.url),warnings:research.warnings}:undefined;return Response.json({token:await tokenFor(session,started,metadata,owner),research:metadata?{provider:metadata.provider,sourceCount:metadata.sourceUrls.length,warnings:metadata.warnings}:undefined});
 }catch(e){return Response.json({error:e instanceof z.ZodError?'Please enter a valid request and priorities.':(e as Error).message},{status:400});}}
export async function GET(request:Request){try{const owner=userId(request);const u=new URL(request.url),phase=u.searchParams.get('phase');const data=await readToken(u.searchParams.get('token')||'');if(data.owner!==owner)throw new Error('This decision belongs to another account.');const {agent}=config();const result=await zoo('/agents/'+agent+'/sessions/'+data.session+'/events?limit=500');const events=Array.isArray(result)?result:result.events||result.items||[];
 // Locate the latest user message: a session contains both criteria and research turns.
 let begin=-1;for(let i=0;i<events.length;i++)if(events[i].event_type==='user.message'||events[i].type==='user.message')begin=i;
 const current=events.slice(begin+1);const done=current.find((e:any)=>e.event_type==='run.finished');
 if(!done)return Response.json({status:'running',progress:current.some((e:any)=>e.event_type==='agent.tool')?'Researching sources':'Thinking through your request'});
 if(done.payload?.status&&done.payload.status!=='succeeded')throw new Error('The research run stopped before finishing. Please retry.');
 const texts=current.filter((e:any)=>e.event_type==='agent.assistant').map((e:any)=>(e.payload?.message?.content||[]).filter((c:any)=>c.type==='text').map((c:any)=>c.text).join(''));let parsed:any;for(const t of texts.reverse()){try{const first=t.indexOf('{'),last=t.lastIndexOf('}');parsed=JSON.parse(t.slice(first,last+1));if(phase==='criteria')parsed=inferenceSchema.parse(parsed);else if(phase==='taste')parsed=tasteSchema.parse(parsed);else parsed=researchSchema.parse(parsed);break;}catch{parsed=undefined;}}
 if(!parsed)throw new Error('ZooWork returned an unexpected response. Please retry.');if(parsed.error)throw new Error(parsed.error);if(phase==='research')for(const c of parsed.candidates)for(const id of Object.keys(c.scores)){const evidence=c.evidence[id]||'';if(!evidence||/no verified evidence|unverified|unconfirmed|not (?:explicitly )?(?:confirmed|specified|detailed)|implies|implying|not in (?:the )?(?:available|supplied)|no (?:explicit|specific)|specifics unconfirmed/i.test(evidence))c.scores[id]=null;}if(phase==='research'&&data.research){const allowed=new Set(data.research.sourceUrls);parsed.candidates=parsed.candidates.filter((c:any)=>c.url&&allowed.has(c.url));if(!parsed.candidates.length)throw new Error('The agent returned no options supported by Tavily sources. Try a more specific request.');parsed.research={provider:data.research.provider,sourceCount:allowed.size,warnings:data.research.warnings};}return Response.json({status:'complete',data:parsed});
 }catch(e){return Response.json({error:(e as Error).message},{status:400});}}

export async function DELETE(request:Request){try{const input:any=await request.json();const data=await readToken(input.token);if(data.owner!==userId(request))throw new Error('This decision belongs to another account.');await zoo(`/agents/${config().agent}/sessions/${data.session}/events`,{events:[{type:"user.interrupt"}]});return Response.json({status:"cancelled"});}catch(e){return Response.json({error:(e as Error).message},{status:400});}}
