'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Brain,Sparkles,ArrowUpRight,SlidersHorizontal,Search,RotateCcw,Check,Plus,ChevronDown,ChevronUp,Layers,Lightbulb,LoaderCircle,Scale,Compass,ShieldCheck} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Slider} from '@/components/ui/slider';
import {demoDecision,examples,rank,type Decision,type Criterion} from '@/lib/decision';
import TasteMemory,{memoryAction} from '@/components/taste-memory';
import {applyDemoTaste,type TasteState} from '@/lib/taste';
import ExpertCouncil from '@/components/expert-council';
import {recallTaste} from '@/lib/moss-client';
export default function Home(){
 const [taste,setTaste]=useState<TasteState|null>(null),[useTaste,setUseTaste]=useState(true),[saved,setSaved]=useState(''),[recall,setRecall]=useState<{docs:{id:string;text:string;score:number}[];ms:number}|null>(null),[memoryWarning,setMemoryWarning]=useState('');
 async function remember(item:any,disposition:string){try{setTaste(await memoryAction({action:'add',memories:[{kind:'decision',label:item.name,disposition,context:JSON.stringify({query,domain:decision?.domain,mode:decision?.mode,priorities:active.map(c=>({label:c.label,weight:c.weight})),evidence:item.evidence})}]}));setSaved(item.name+' saved. Learn my taste to update your profile.');}catch(e){setError((e as Error).message);}}
 const [query,setQuery]=useState(examples[0].query),[decision,setDecision]=useState<Decision|null>(null),[mode,setMode]=useState<'demo'|'live'>('live'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[token,setToken]=useState(''),[expanded,setExpanded]=useState<string|null>(null),[showAll,setShowAll]=useState(false),[showForgot,setShowForgot]=useState(false),[tradeoff,setTradeoff]=useState(50);const run=useRef(0);
 const active=decision?.criteria.filter(c=>c.selected)||[];
 const ranked=useMemo(()=>rank(decision?.candidates||[],decision?.criteria||[]),[decision]);
 async function runPhase(phase:'criteria'|'research',q=query,criteria=decision?.criteria){const id=++run.current;setError('');setBusy(phase==='criteria'?'Creating your decision criteria…':'Finding options and checking sources…');if(phase==='criteria'){setDecision(null);setShowAll(false);setShowForgot(false);setTradeoff(50);}
 try{if(mode==='demo'){await new Promise(r=>setTimeout(r,650));if(id!==run.current)return;const sample=demoDecision(q);if(useTaste&&taste)sample.criteria=applyDemoTaste(sample.criteria,taste.profile);if(phase==='criteria')setDecision({...sample,candidates:[]});else setDecision(prev=>prev?{...prev,candidates:sample.candidates}:sample);return;}
 let recalled=recall;if(phase==='criteria'&&useTaste&&taste?.memories.length){setBusy('Recalling what matters to you…');setMemoryWarning('');try{recalled=await recallTaste(q,taste.profile);if(id!==run.current)return;setRecall(recalled);}catch(e){setMemoryWarning('Moss recall unavailable. Using your saved preference profile: '+(e as Error).message);}setBusy('Creating your decision criteria…');}
 const r=await fetch('/api/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phase,query:q,criteria,token,useTaste,recalledIds:recalled?.docs.map(d=>d.id)})});const start:any=await r.json();if(!r.ok)throw new Error(start.error);setToken(start.token);if(start.research)setDecision(prev=>prev?{...prev,research:start.research}:prev);
 for(let i=0;i<300;i++){await new Promise(r=>setTimeout(r,2000));if(id!==run.current)return;const poll=await fetch('/api/decision?phase='+phase+'&token='+encodeURIComponent(start.token));const result:any=await poll.json();if(!poll.ok)throw new Error(result.error);if(result.status==='complete'){if(phase==='criteria')setDecision({...result.data,candidates:[],mode:'live'});else {if(!result.data.candidates.length)throw new Error('No verified options found. Try a more specific request.');setDecision(prev=>prev?{...prev,candidates:result.data.candidates,research:result.data.research}:prev);}return;}}
 throw new Error('Research is taking longer than expected. Please try again.');
 }catch(e){if(id===run.current)setError((e as Error).message);}finally{if(id===run.current)setBusy('');}}
 function update(id:string,patch:Partial<Criterion>){setDecision(d=>d?{...d,criteria:d.criteria.map(c=>c.id===id?{...c,...patch}:c)}:d);}
 function reset(){if(busy&&token)void fetch('/api/decision',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});run.current++;setBusy('');setError('');setRecall(null);setMemoryWarning('');setDecision(null);setToken('');setExpanded(null);setShowForgot(false);}
 function switchMode(next:'demo'|'live'){reset();setMode(next);}
 function explore(v:number){setTradeoff(v);setDecision(d=>{if(!d)return d;const selected=d.criteria.filter(c=>c.selected);if(selected.length<2)return d;const a=selected[0].id,b=selected[1].id;return {...d,criteria:d.criteria.map(c=>c.id===a?{...c,weight:Math.max(1,100-v)}:c.id===b?{...c,weight:Math.max(1,v)}:c)};});}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'set_decision_request',description:'Enter a decision request in FindWise. Does not start research.',inputSchema:{type:'object',properties:{query:{type:'string',minLength:8,maxLength:1500}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(typeof input.query!=='string'||input.query.length<8||input.query.length>1500)throw new Error('Enter 8–1500 characters.');setQuery(input.query);reset();return {query:input.query,status:'ready'};}},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort();},[]);
 return <div className="app-shell"><header><a className="brand" href="/" aria-label="FindWise home"><span className="brand-icon"><Compass size={23}/></span>findwise<span className="brand-period">.</span></a><span className="header-label">YOUR PRIORITIES. YOUR DECISION.</span><div className="mode-picker"><button onClick={()=>switchMode('live')} className={mode==='live'?'current':''}>Live research</button><button onClick={()=>switchMode('demo')} className={mode==='demo'?'current':''}>Demo</button></div></header>
 <main><div className="intro"><div className="eyebrow"><Sparkles size={15}/> A SEARCH THAT GETS YOU</div><h1>Find what matters<span>.</span></h1><p>From a new apartment to your next accountant.<br className="mobile-break"/> Tell us what you need. We’ll figure out what to look for.</p></div>
 <TasteMemory state={taste} onChange={setTaste} enabled={useTaste} onEnabled={setUseTaste}/>{recall&&useTaste&&<div className="moss-recall" title={recall.docs.map(d=>d.text).join('\n')}><Brain size={14}/>{recall.docs.length} relevant memories recalled by Moss · {recall.ms.toFixed(1)} ms local retrieval</div>}{memoryWarning&&<p className="coverage">{memoryWarning}</p>}<section className="query-card"><div className="query-label"><span><Search size={18}/> What are you deciding?</span><span className="query-tag">ANYTHING, REALLY</span></div><form onSubmit={e=>{e.preventDefault();runPhase('criteria');}}><textarea aria-label="Describe your decision" maxLength={1500} value={query} onChange={e=>{setQuery(e.target.value);if(decision)reset();}} placeholder="I need a dress for a beach wedding under $300, but I hate dry cleaning…"/><div className="query-bottom"><span><Sparkles size={15}/> Your words become your filters</span><button className="primary" disabled={!!busy||query.trim().length<8} type="submit">{busy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>}Create my criteria</button></div></form></section>
 <div className="examples"><span>Try a decision</span>{examples.map(ex=><button key={ex.label} disabled={!!busy} onClick={()=>{reset();setQuery(ex.query);}}>{ex.label}<Plus size={13}/></button>)}</div>
 {mode==='demo'&&<div className="demo-note"><Layers size={16}/> Demo mode uses illustrative options and scores. Prices and attributes are not live research.</div>}
 {error&&<div className="error" role="alert">{error}<button onClick={()=>switchMode('demo')}>Explore demo</button></div>}
 {busy&&<div className="loading" role="status"><LoaderCircle className="spin" size={22}/><div><strong>{busy}</strong><p>{mode==='live'?'ZooWork is working through your request. This can take several minutes.':'Putting together the demo decision.'}</p></div><button onClick={reset}>Cancel</button></div>}
 {!decision&&!busy&&<div className="empty-workspace"><div className="empty-step"><span>01</span><Sparkles/><h3>Filters, invented for you</h3><p>Your saved taste transfers to each new domain, with your request taking priority.</p></div><div className="empty-step"><span>02</span><SlidersHorizontal/><h3>Make your priorities count</h3><p>Choose what matters and dial in how much it matters.</p></div><div className="empty-step"><span>03</span><Scale/><h3>A decision you can explain</h3><p>Compare matches, see the tradeoffs, and make the call.</p></div></div>}
 {decision&&<div className="workspace"><aside><div className="panel-title"><div><div className="eyebrow">01 / YOUR DECISION DNA</div><h2>What matters to you</h2></div><SlidersHorizontal size={20}/></div><div className="domain-chip"><Layers size={14}/>{decision.domain}<span>{decision.criteria.length} criteria</span></div><p className="aside-description">We selected priorities from your request. Adjust them to make this decision yours.</p><div className="criteria-list">{(showAll?decision.criteria:decision.criteria.filter(c=>c.selected)).map(c=><div className={'criterion '+(c.selected?'selected':'')} key={c.id}><div className="criterion-top"><label htmlFor={c.id}><Checkbox id={c.id} checked={c.selected} onCheckedChange={v=>update(c.id,{selected:!!v})}/><span>{c.label}</span></label>{c.selected&&<span className="weight">{c.weight}<small>/100</small></span>}</div>{c.selected&&<><Slider aria-label={c.label+' importance'} value={[c.weight]} max={100} step={1} onValueChange={v=>update(c.id,{weight:v[0]})}/><div className="criterion-meta"><span>{c.hard?'CONSTRAINT':'PRIORITY'}</span><span title={c.tasteReason||c.reason}>{c.tasteReason?'From your taste':'From your request'}</span></div></>}</div>)}</div><button className="show-more" onClick={()=>setShowAll(!showAll)}>{showAll?'Show selected priorities':`Explore all ${decision.criteria.length} criteria`}{showAll?<ChevronUp size={15}/>:<ChevronDown size={15}/>}</button><button className="forgot-button" onClick={()=>setShowForgot(!showForgot)}><Lightbulb size={18}/>What did I forget?<span>{decision.forgotten.length}</span></button>{showForgot&&<div className="forgotten">{decision.forgotten.map(f=>{const c=decision.criteria.find(c=>c.id===f.id);return c&&<div key={f.id}><strong>{c.label}</strong><p>{f.explanation}</p><button disabled={c.selected} onClick={()=>update(c.id,{selected:true})}>{c.selected?<Check size={14}/>:<Plus size={14}/>} {c.selected?'Added to priorities':'Add this priority'}</button></div>;})}</div>}
 <button className="primary find-button" disabled={!!busy||!active.some(c=>c.weight>0)} onClick={()=>runPhase('research')}><Search size={17}/>{decision.candidates.length?'Refresh research':'Find my matches'}</button></aside>
 <section className="results"><div className="results-heading"><div><div className="eyebrow">02 / YOUR SHORTLIST</div><h2>{ranked.length?'Good options. Clear tradeoffs.':'Your shortlist starts here.'}</h2></div>{ranked.length>0&&<span className="count">{ranked.length} matches</span>}</div>
 {ranked.length===0?<div className="results-empty"><span className="empty-compass"><Compass size={40}/></span><h3>A little clarity goes a long way.</h3><p>Review your priorities, then find options<br/> ranked around what matters to you.</p><div><Check size={15}/>{active.length} priorities selected</div></div>:<><div className="tradeoff"><div className="tradeoff-heading"><span><Scale size={17}/> Tradeoff explorer</span><small>RANKINGS UPDATE INSTANTLY</small></div><div className="tradeoff-labels"><span>{active[0]?.label||'Select a priority'}</span><span>{active[1]?.label||'Select another priority'}</span></div><Slider aria-label="Tradeoff between first two selected priorities" value={[tradeoff]} onValueChange={v=>explore(v[0])} disabled={active.length<2}/><p>Shift the balance between your first two priorities, or adjust each one individually.</p></div><ExpertCouncil decision={decision} query={query} profile={useTaste?taste?.profile:undefined}/>{saved&&<p className="saved-note" role="status">{saved}</p>}<div className="ranking-note"><ShieldCheck size={15}/>{decision.mode==='demo'?'Illustrative matches · no verified sources':decision.research?.provider==='tavily'?`Tavily research · ${decision.research.sourceCount} sources`:'Source-based research · confirm details before committing'}<span>Weighted personal match</span></div>
 {!active.some(c=>c.weight>0)&&<div className="error">Select at least one priority with a weight above zero to rank options.</div>}
 {decision.research?.warnings.map((warning,i)=><p className="coverage" role="status" key={i}>{warning}</p>)}
 {ranked.map((item,index)=>{const strongest=[...active].filter(c=>typeof item.scores[c.id]==='number').sort((a,b)=>b.weight*(item.scores[b.id]??0)-a.weight*(item.scores[a.id]??0)).slice(0,2);return <article className={'result-card '+(index===0&&item.eligible?'winner':'')} key={item.id}><div className="result-top"><span className="rank-number">{String(index+1).padStart(2,'0')}</span><div className="result-main"><div className="result-name"><h3>{item.name}</h3>{index===0&&item.eligible&&<span className="best-match">BEST MATCH</span>}{!item.eligible&&<span className="constraint-fail">Fails a constraint</span>}</div><p>{item.subtitle}</p></div><div className="score"><strong>{Math.round(item.score)}<small>%</small></strong><span>personal match</span></div></div><div className="result-body"><div className="result-reasons">{strongest.map(c=><span key={c.id}><Check size={13}/>{c.label}</span>)}</div><p className="rationale">{strongest.length?`Ranks ${index===0?'highest':'here'} for ${strongest.map(c=>c.label.toLowerCase()).join(' and ')} at your current weights. `:''}{item.caveat}</p>{item.coverage<1&&<p className="coverage">{Math.round(item.coverage*100)}% evidence coverage. Unknown attributes earn no points.</p>}</div><div className="remember-actions"><button onClick={()=>remember(item,'like')}>Like</button><button onClick={()=>remember(item,'dislike')}>Dislike</button><button onClick={()=>remember(item,'chosen')}>Remember this choice</button></div><div className="result-footer"><span>{item.price||'Price not verified'}</span><button onClick={()=>setExpanded(expanded===item.id?null:item.id)}>Why this match?{expanded===item.id?<ChevronUp size={14}/>:<ChevronDown size={14}/>}</button>{item.url&&<a href={item.url} target="_blank" rel="noopener noreferrer">View source<ArrowUpRight size={14}/></a>}</div>{expanded===item.id&&<div className="breakdown"><h4>The math behind the match</h4>{active.map(c=><div className="breakdown-row" key={c.id}><div><strong>{c.label}</strong><p>{item.evidence[c.id]||'No verified evidence available.'}</p></div><div className="breakdown-values"><span>{item.scores[c.id]===null||item.scores[c.id]===undefined?'Unknown':item.scores[c.id]+'/100'}</span><small>{Math.round(c.weight/active.reduce((s,c)=>s+c.weight,0)*100)||0}% weight</small></div></div>)}<p className="formula">Match = Σ (normalized priority weight × attribute score). Unknown attributes score zero.</p></div>}</article>;})}</>}
 </section></div>}
 <footer><span>findwise<span className="brand-period">.</span> <span className="footer-tag">A little less searching. A lot more clarity.</span></span><span>ZooWork runs · Tavily searches · Moss recalls · BAND collaborates</span></footer></main></div>;
}
