'use client';
import {useEffect,useRef,useState} from 'react';
import {Users,LoaderCircle,ArrowUpRight} from 'lucide-react';
import {rank,type Decision} from '@/lib/decision';
import type {TasteProfile} from '@/lib/taste';
const roles=[['taste','Taste','minimal|design|quiet|quality|sustainab'],['value','Value','budget|afford|value|cost|price'],['quality','Quality','quality|durab|reliab|material|expert'],['practical','Practicality','comfort|light|conven|walk|ship|battery|organization'],['evidence','Evidence','review|return|warranty|policy|cancel']];
export default function ExpertCouncil({decision,query,profile}:{decision:Decision;query:string;profile?:TasteProfile}){const [state,setState]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const run=useRef(0);const signature=JSON.stringify({query,criteria:decision.criteria,candidates:decision.candidates});useEffect(()=>{run.current++;setState(null);setBusy(false);setError('');},[signature]);
 async function start(){const n=++run.current;setBusy(true);setError('');try{if(decision.mode==='demo'){const reports=roles.map(([role,label,pattern])=>{const lens=decision.criteria.filter(c=>new RegExp(pattern,'i').test(c.label)).map(c=>({...c,selected:true,weight:100}));const best=rank(decision.candidates,lens)[0];return {role,label,preferredId:best?.id,summary:lens.length?`${best.name} leads on ${lens.slice(0,2).map(c=>c.label.toLowerCase()).join(' and ')}.`:'No relevant attributes are available for this lens.',tradeoff:'Illustrative score-based lens. No managed expert or BAND call in demo mode.',confidence:'low'};});setState({status:'complete',reports,stage:'Demo: five deterministic comparison lenses'});return;}
 const r=await fetch('/api/council',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,decision,useTaste:!!profile})});let s:any=await r.json();if(!r.ok)throw new Error(s.error);if(n!==run.current)return;setState(s);for(let i=0;i<180&&s.status==='running';i++){await new Promise(r=>setTimeout(r,4000));if(n!==run.current)return;const r=await fetch('/api/council?id='+encodeURIComponent(s.id));s=await r.json();if(!r.ok)throw new Error(s.error);setState(s);}if(s.status==='error')throw new Error(s.error);if(s.status==='running')throw new Error('Review is taking longer than expected.');}catch(e){if(n===run.current)setError((e as Error).message);}finally{if(n===run.current)setBusy(false);}}
 return <div className="council"><div className="council-heading"><div><span><Users size={18}/> A second opinion, from every angle.</span><p>{decision.mode==='demo'?'Illustrative comparison lenses':'ZooWork specialists discuss your shortlist in BAND.'}</p></div><button disabled={busy} onClick={start}>{busy?<LoaderCircle className="spin" size={15}/>:<Users size={15}/>} {state?'Review again':'Ask the council'}</button></div>{state&&<><p className="council-stage" role="status">{state.stage}</p><div className="expert-grid">{state.reports.map((r:any)=><div className={'expert '+(r.role==='decision'?'consensus':'')} key={r.role}><div><strong>{r.label}</strong><small>{r.confidence} confidence</small></div><p>{r.summary}</p><span>{r.tradeoff}</span></div>)}</div>{state.room&&<span className="band-proof">BAND room: {state.room}</span>}<p className="council-footnote">Expert advice supplements your weighted ranking. Changing priorities requires a fresh review.</p></>}{error&&<p className="error" role="alert">{error}</p>}</div>;
}
