'use client';
import {useEffect,useState} from 'react';
import {Brain,Plus,ThumbsUp,ThumbsDown,Trash2,LoaderCircle,ChevronDown,ChevronUp,Sparkles} from 'lucide-react';
import {axes,emptyProfile,type TasteState} from '@/lib/taste';
export async function memoryAction(body:unknown){const r=await fetch('/api/taste',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v:any=await r.json();if(!r.ok)throw new Error(v.error);return v as any;}
export default function TasteMemory({state,onChange,enabled,onEnabled}:{state:TasteState|null;onChange:(s:TasteState)=>void;enabled:boolean;onEnabled:(v:boolean)=>void}){
 const [open,setOpen]=useState(false),[input,setInput]=useState(''),[kind,setKind]=useState<'brand'|'note'>('brand'),[busy,setBusy]=useState(''),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/taste').then(async r=>{const v:any=await r.json();if(!r.ok)throw new Error(v.error);onChange(v);}).catch(e=>setError(e.message));},[]);
 async function act(body:any){setError('');setBusy('Saving…');try{onChange(await memoryAction(body));}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function learn(){setError('');setBusy('Learning from your saved decisions…');try{const {token}=await memoryAction({action:'infer'});for(let i=0;i<120;i++){await new Promise(r=>setTimeout(r,2000));const r=await fetch('/api/decision?phase=taste&token='+encodeURIComponent(token));const v:any=await r.json();if(!r.ok)throw new Error(v.error);if(v.status==='complete'){onChange(await memoryAction({action:'commit',token,profile:v.data}));return;}}throw new Error('Learning took too long. Your saved choices are safe; try again.');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 const profile=state?.profile||emptyProfile;
 return <section className="taste-panel"><div className="taste-header"><div className="taste-symbol"><Brain size={21}/></div><div><div className="eyebrow">YOUR TASTE, ACROSS EVERY DECISION</div><h2>{profile.traits.length?'A search that remembers you.':'Start with things you already love.'}</h2></div><button className="taste-open" onClick={()=>setOpen(!open)}>{open?'Close':'Your taste'}{open?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button></div>
 <p className="taste-summary">{profile.summary}</p>
 {profile.traits.length>0&&<div className="taste-chips">{profile.traits.map(t=><span key={t.id} title={t.reason}>{axes.find(a=>a.id===t.id)?.label}<b>{Math.round(t.value*100)}%</b></span>)}</div>}
 <div className="taste-bottom"><label><input type="checkbox" checked={enabled} onChange={e=>onEnabled(e.target.checked)}/> Use my taste in this search</label><span>{state?.memories.length||0} saved signals · Private preference memory</span></div>
 {open&&<div className="taste-editor"><div className="taste-input-heading"><h3>No questionnaire. Just things you like.</h3><p>Brand likes are clues, not facts about you. You can correct every inferred trait.</p></div><div className="taste-kind"><button className={kind==='brand'?'current':''} onClick={()=>setKind('brand')}>Brands</button><button className={kind==='note'?'current':''} onClick={()=>setKind('note')}>Decision / preference</button></div><textarea aria-label="Add preference signals" value={input} maxLength={3000} onChange={e=>setInput(e.target.value)} placeholder={kind==='brand'?'Muji, Patagonia, Aesop…':'I chose a quiet hotel over a cheaper hotel next to nightlife.'}/><div className="taste-actions">{(['like','dislike'] as const).map(disposition=><button disabled={!!busy||!input.trim()} key={disposition} onClick={()=>{const labels=kind==='brand'?input.split(',').map(s=>s.trim()).filter(Boolean).slice(0,20):[input.trim().slice(0,250)];void act({action:'add',memories:labels.map(label=>({kind,label,disposition,context:kind==='note'?input:''}))});setInput('');}}>{disposition==='like'?<ThumbsUp size={14}/>:<ThumbsDown size={14}/>}Save {disposition==='like'?'likes':'dislikes'}</button>)}<button disabled={!!busy||!state?.memories.length} onClick={learn}><Sparkles size={14}/>Learn my taste</button><button disabled={!!busy} onClick={()=>act({action:'starter'})}>Add example likes</button></div>
 {profile.traits.length>0&&<div className="trait-grid">{profile.traits.map(t=><div className="trait" key={t.id}><div><strong>{axes.find(a=>a.id===t.id)?.label}</strong><span>{Math.round(t.value*100)}%</span></div><input aria-label={(axes.find(a=>a.id===t.id)?.label||t.id)+' preference'} type="range" min="0" max="100" defaultValue={Math.round(t.value*100)} key={t.id+'-'+t.value} onPointerUp={e=>{const value=Number(e.currentTarget.value)/100;void act({action:'update',profile:{...profile,traits:profile.traits.map(x=>x.id===t.id?{...x,value,confidence:1,reason:'Explicitly adjusted by you.'}:x)}});}} onKeyUp={e=>{if(!e.key.startsWith('Arrow'))return;const value=Number(e.currentTarget.value)/100;void act({action:'update',profile:{...profile,traits:profile.traits.map(x=>x.id===t.id?{...x,value,confidence:1,reason:'Explicitly adjusted by you.'}:x)}});}}/><p>{t.reason}</p><small>{Math.round(t.confidence*100)}% confidence · {t.confidence<.75?'Tentative inference':'Confirmed signal'}</small><button aria-label={'Remove '+t.id+' trait'} onClick={()=>act({action:'update',profile:{...profile,traits:profile.traits.filter(x=>x.id!==t.id)}})}><Trash2 size={13}/></button></div>)}</div>}
 <div className="memory-history"><h3>Your decision memory</h3>{state?.memories.slice(0,15).map(m=><div key={m.id}><span className={'memory-disposition '+m.disposition}>{m.disposition}</span><span>{m.label}<small>{m.kind} · {new Date(m.createdAt).toLocaleDateString()}</small></span><button disabled={!!busy} aria-label={'Forget '+m.label} onClick={()=>act({action:'remove',id:m.id})}><Trash2 size={14}/></button></div>)}</div></div>}
 {busy&&<p className="taste-status" role="status"><LoaderCircle className="spin" size={14}/>{busy}</p>}{error&&<p className="error" role="alert">{error}{error.startsWith('Sign in')&&<a href="/signin-with-chatgpt">Sign in with ChatGPT</a>}</p>}</section>;
}
