export type Criterion = {id:string; label:string; selected:boolean; weight:number; reason:string; hard?:boolean; tasteReason?:string};
export type Candidate = {id:string; name:string; subtitle:string; price:string|null; url:string|null; scores:Record<string,number|null>; evidence:Record<string,string>; caveat:string; verified?:boolean};
export type Decision = {domain:string; criteria:Criterion[]; forgotten:{id:string; explanation:string}[]; candidates:Candidate[]; mode:'demo'|'live'; research?:{provider:'tavily';sourceCount:number;warnings:string[]}};
export const examples = [
 {label:'A lasting backpack',query:'Find me a backpack for everyday work and travel under $200.'},
 {label:'A weekend hotel',query:'Find me a hotel in San Francisco for a quiet weekend under $250 per night.'},
 {label:'Startup accountant',query:'I need a CPA for my early-stage AI startup in California. Under $500 a month, with R&D tax credit experience.'},
 {label:'A better apartment',query:'Find an apartment in San Francisco under $3,000. I work from home, have a dog, and need lots of natural light.'},
 {label:'Beach wedding dress',query:'I need a dress for a warm beach wedding in Cabo, under $300, but I hate dry cleaning.'},
 {label:'Travel camera',query:'I want a camera for travel under $1,500. Lightweight, great in low light, and easy for a beginner.'}
];
const domains:Record<string,{title:string; labels:string[]; selected:number[]; names:string[]; descriptions:string[]; prices:string[]; forgotten:number}>={
 backpack:{title:'Everyday backpacks',labels:['Under budget','Durability','Minimal design','Comfortable carry','Organization','Premium materials','Laptop protection','Lightweight','Warranty','Neutral colors','Weather resistance','Sustainable materials','Versatile styling','Repairability','Customer reviews','Return policy'],selected:[0,3,4,6],names:['The quiet commuter','The trail-to-office pack','The featherweight tote-pack','The everyday essential'],descriptions:['Clean lines · structured everyday carry','Rugged build · practical organization','Light design · simple silhouette','Low-cost carry · basic protection'],prices:['$165','$195','$135','$65'],forgotten:8},
 hotel:{title:'Weekend hotels',labels:['Under budget','Quiet environment','Design quality','Walkable location','Service quality','Clean modern rooms','Sleep comfort','Cancellation policy','Room space','Local character','Breakfast','Public transit','Sustainability','Reliable Wi-Fi','Customer reviews','Hidden fees'],selected:[0,1,3,6],names:['The garden retreat','The considered city stay','The waterfront hideaway','The budget city base'],descriptions:['Calm courtyard · restful surroundings','Modern rooms · attentive service','Scenic location · characterful interiors','Central convenience · simple rooms'],prices:['$215 / night','$245 / night','$235 / night','$135 / night'],forgotten:15},
 cpa:{title:'Startup accounting',labels:['Affordable monthly fee','Startup experience','R&D tax credits','California expertise','AI / SaaS clients','Clear communication','Bookkeeping included','Tax filing included','Fast onboarding','Dedicated accountant','Transparent pricing','Payroll support','Fundraising support','Security & privacy','Founder references','Flexible contract'],selected:[0,1,2,3,4],names:['Launch Ledger','Founders & Co.','Pacific Tax Studio','Signal Accounting'],descriptions:['Built for pre-seed teams','A dedicated startup finance partner','California tax specialists','Lean bookkeeping for lean teams'],prices:['$350 / month','$495 / month','$425 / month','$240 / month'],forgotten:13},
 apartment:{title:'Apartment search',labels:['Affordable rent','Natural light','Pet friendly','Quiet for remote work','Commute time','Walkable groceries','In-unit laundry','Space for a desk','Neighborhood safety','Lease flexibility','Reliable internet','Parking','Outdoor space','Energy efficiency','Maintenance quality','Move-in costs'],selected:[0,1,2,3,7],names:['The sunlit corner','The neighborhood retreat','The connected studio','The spacious hideaway'],descriptions:['Bright corner apartment · Inner Sunset','Quiet one bedroom · Noe Valley','Compact studio · Hayes Valley','Large one bedroom · Richmond'],prices:['$2,850 / month','$2,975 / month','$2,650 / month','$2,700 / month'],forgotten:15},
 dress:{title:'Wedding guest dresses',labels:['Under budget','Breathable fabric','Wedding appropriate','Machine / hand washable','Comfortable fit','Elegant style','Easy returns','Fast shipping','Size availability','Wrinkle resistant','Versatile styling','Inclusive sizing','Sustainable materials','Customer reviews','Color options','Travel friendly'],selected:[0,1,2,3,4],names:['The linen midi','The coastal wrap','The satin slip','The everyday occasion'],descriptions:['Airy linen blend · relaxed silhouette','Lightweight cotton · adjustable waist','Fluid satin · evening silhouette','Cotton poplin · easy movement'],prices:['$145','$198','$265','$89'],forgotten:6},
 camera:{title:'Travel cameras',labels:['Under budget','Lightweight','Low-light performance','Beginner friendly','Image quality','Battery life','Weather resistance','Lens ecosystem','Video quality','Stabilization','Compact size','Autofocus','Charging via USB','Ergonomics','Warranty & returns','Used availability'],selected:[0,1,2,3,4],names:['The pocket companion','The versatile mirrorless','The adventure compact','The entry-level favorite'],descriptions:['Compact body · everyday travel','Interchangeable lens · room to grow','Rugged compact · outdoor ready','Simple controls · excellent value'],prices:['$899','$1,299','$1,099','$749'],forgotten:5},
 general:{title:'Your decision',labels:['Affordability','Overall quality','Reliability','Customer reviews','Availability','Convenience','Ease of use','Long-term value','Support quality','Flexibility','Location fit','Time saved','Sustainability','Warranty / cancellation','Experience fit','Hidden costs'],selected:[0,1,2,3,7],names:['The balanced option','The premium choice','The convenient choice','The budget option'],descriptions:['Strong across your priorities','More quality, higher cost','Quick and straightforward','A lower-cost starting point'],prices:['Example price','Example price','Example price','Example price'],forgotten:15}
};
export function demoDecision(query:string):Decision {
 const key=/backpack|rucksack/i.test(query)?'backpack':/hotel|stay|weekend/i.test(query)?'hotel':/dress|wedding|fabric/i.test(query)?'dress':/apartment|rent|housing/i.test(query)?'apartment':/camera|photo/i.test(query)?'camera':/cpa|account|tax/i.test(query)?'cpa':'general'; const d=domains[key];
 const criteria=d.labels.map((label,i)=>({id:'c'+i,label,selected:d.selected.includes(i),weight:i===0?65:i===2?85:60,reason:d.selected.includes(i)?'Inferred from your request':'Worth considering',hard:i===0}));
 const matrix=[[83,94,90,89,92],[58,98,97,93,95],[68,78,96,84,82],[98,67,54,74,70]];
 const candidates=d.names.map((name,n)=>({id:'option'+n,name,subtitle:d.descriptions[n],price:d.prices[n],url:null,scores:Object.fromEntries(criteria.map((c,i)=>[c.id,i<5?matrix[n][i]:Math.max(45,Math.min(98,58+((i*13+n*19)%40)))])),evidence:Object.fromEntries(criteria.map((c,i)=>[c.id,'Illustrative '+c.label.toLowerCase()+' assessment; not verified research.'])),caveat:['Balanced choice; confirm the details before committing.','Higher cost in exchange for deeper specialization.','A focused fit with fewer extras.','Strong on price; compromises on specialist features.'][n],verified:false}));
 return {domain:d.title,criteria,candidates,forgotten:[{id:'c'+d.forgotten,explanation:key==='dress'?'Sizing varies across brands. A flexible return policy can matter as much as the dress itself.':key==='cpa'?'Your accountant handles sensitive financial records. Ask how they secure access and share files.':key==='apartment'?'Deposits, pet fees, and moving costs can change the true cost of an apartment.':'The costs after your purchase can change which option is the best value.'}],mode:'demo'};
}
export function rank(candidates:Candidate[],criteria:Criterion[]) {
 const active=criteria.filter(c=>c.selected&&c.weight>0),total=active.reduce((s,c)=>s+c.weight,0);
 return candidates.map(item=>{let earned=0,known=0;for(const c of active){const v=item.scores[c.id];if(typeof v==='number'){earned+=c.weight*v;known+=c.weight;}}return {...item,eligible:!active.some(c=>c.hard&&item.scores[c.id]===0),score:total?earned/total:0,coverage:total?known/total:0};}).sort((a,b)=>Number(b.eligible)-Number(a.eligible)||b.score-a.score);
}
