import {z} from 'zod';
import type {Criterion} from './decision';
export const axes=[{id:'minimalism',label:'Minimal design'},{id:'quality',label:'Quality over price'},{id:'function',label:'Function over flash'},{id:'timeless',label:'Timeless choices'},{id:'calm',label:'Calm environments'},{id:'sustainability',label:'Sustainability'},{id:'structure',label:'Structure & expertise'},{id:'adventure',label:'New experiences'}] as const;
export const traitSchema=z.object({id:z.enum(['minimalism','quality','function','timeless','calm','sustainability','structure','adventure']),value:z.number().min(0).max(1),confidence:z.number().min(0).max(1),reason:z.string().max(500)});
export const tasteSchema=z.object({summary:z.string().max(500),traits:z.array(traitSchema).max(8)});
export type TasteProfile=z.infer<typeof tasteSchema>;
export type Memory={id:string;kind:'brand'|'decision'|'note';label:string;disposition:'like'|'dislike'|'chosen';context:string;createdAt:number};
export type TasteState={profile:TasteProfile;memories:Memory[];updatedAt:number|null;providers:{moss:boolean;band:boolean};warning?:string};
export const emptyProfile:TasteProfile={summary:'Your preferences will take shape as you save things you like.',traits:[]};
export function starterProfile():TasteProfile{return {summary:'You gravitate toward useful, considered things that last. Treat these as starting hypotheses, not fixed rules.',traits:[{id:'minimalism',value:.91,confidence:.68,reason:'Muji and Apple suggest a preference for simple design.'},{id:'quality',value:.88,confidence:.65,reason:'Patagonia and Aesop suggest willingness to invest in quality.'},{id:'function',value:.86,confidence:.72,reason:'Patagonia and Uniqlo suggest practical everyday utility.'},{id:'timeless',value:.83,confidence:.62,reason:'Muji and Uniqlo suggest understated, lasting choices.'},{id:'calm',value:.75,confidence:.44,reason:'Simple aesthetics may translate into calmer surroundings; confirm this.'},{id:'sustainability',value:.76,confidence:.53,reason:'Patagonia suggests interest in sustainability; brand likes are an imperfect signal.'}]};}
const rules:Record<string,RegExp>={minimalism:/clean|modern|minimal|neutral|design|silhouette|versatile/,quality:/quality|materials|fabric|experience|expert|reliability|durability|reviews|maintenance|service/,function:/practical|comfort|battery|storage|laundry|use|walkable|commute|reliable|durable|weight/,timeless:/versatile|classic|long.term|durab|warranty|value/,calm:/quiet|noise|calm|peace|neighborhood/,sustainability:/sustainab|environment|energy|ethical/,structure:/structured|teaching|expert|communication|support|training/,adventure:/novel|adventure|local|creative|explor/};
export function applyDemoTaste(criteria:Criterion[],profile:TasteProfile):Criterion[]{return criteria.map(c=>{if(c.hard)return c;const hits=profile.traits.filter(t=>t.value>=.65&&t.confidence>=.35&&rules[t.id]?.test(c.label.toLowerCase())).sort((a,b)=>b.value*b.confidence-a.value*a.confidence);if(!hits.length)return c;const t=hits[0];return {...c,selected:true,weight:Math.max(c.weight,Math.round(50+t.value*t.confidence*45)),tasteReason:`Your ${axes.find(a=>a.id===t.id)?.label.toLowerCase()} preference carries into ${c.label.toLowerCase()}.`,reason:t.reason};});}
export function tasteVector(profile:TasteProfile):number[]{return axes.map(a=>{const t=profile.traits.find(t=>t.id===a.id);return t?(t.value-.5)*2*t.confidence:0;});}
export function contextVector(query:string,profile:TasteProfile):number[]{const base=tasteVector(profile);return axes.map((a,i)=>rules[a.id]?.test(query.toLowerCase())?Math.max(base[i],.8):base[i]||.1);}
